dist: bionic
language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - setup=basic
  matrix:
    - laravel=^6.0
    - laravel=^7.0
    - laravel=^8.0
    - setup=stable laravel=^6.0
    - setup=stable laravel=^7.0
    - setup=stable laravel=^8.0
    - setup=lowest laravel=^6.0
    - setup=lowest laravel=^7.0
    - setup=lowest laravel=^8.0

before_install:
  - composer config discard-changes true

before_script:
  - composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest
  - java -Djava.library.path=./DynamoDBLocal_lib -jar dynamodb_local/DynamoDBLocal.jar --port 3000 &
  - sleep 2
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit -c phpunit.xml

matrix:
  include:
    - php: 7.3
      env: setup=coveralls coverage=yes laravel=^6.0
  allow_failures:
    - env: setup=coveralls coverage=yes laravel=^6.0
  fast_finish: true
