dist: bionic
language: php

php:
  - 7.3

before_install:
  - composer config discard-changes true

before_script:
  - composer install --prefer-dist --no-interaction
  - java -Djava.library.path=./DynamoDBLocal_lib -jar dynamodb_local/DynamoDBLocal.jar --port 3000 &
  - sleep 2
  - composer update --prefer-dist --no-interaction --prefer-stable

script:
  - vendor/bin/phpunit -c phpunit.xml

matrix:
  fast_finish: true
